### ISSUE TITLE
Complete Pin Out for the MKS Nano 6

### ISSUE THREAD

**Issue by zentaur1ger** [blacknet76/FlyingBear-Reborn-2#1]
Just received this file from Flying Bear Support and thought it made sense to share it in your repo.

[MKS Nano6 V3.3_002 PIN Reborn2.pdf](https://github.com/blacknet76/FlyingBear-Reborn-2/files/12664128/MKS.Nano6.V3.3_002.PIN.Reborn2.pdf)

**Comment by blacknet76** [comment]
Thank you I added it to the repo
